// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsgq43gkRl6TWh4GWTjXvWJR9uIsV6jOA',
    appId: '1:549410281065:web:d0a7ec0390df3ab26ab4f8',
    messagingSenderId: '549410281065',
    projectId: 'udemymultistore',
    authDomain: 'udemymultistore.firebaseapp.com',
    storageBucket: 'udemymultistore.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpn_It3Nr4QYm-66mQQPZc8jl6f0ECrcE',
    appId: '1:549410281065:android:23eab34e2539d6df6ab4f8',
    messagingSenderId: '549410281065',
    projectId: 'udemymultistore',
    storageBucket: 'udemymultistore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-MrAlnfcVdBgGBmP8knhpe2wOP9cYi9M',
    appId: '1:549410281065:ios:d5c0ef5ad4e60f8b6ab4f8',
    messagingSenderId: '549410281065',
    projectId: 'udemymultistore',
    storageBucket: 'udemymultistore.firebasestorage.app',
    iosBundleId: 'com.example.multistore',
  );
}
